// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaEyNLQCzuruMWAV6JpH6tQWHdbeGkgq4',
    appId: '1:452972580172:web:c9f1396b750243e6e853e9',
    messagingSenderId: '452972580172',
    projectId: 'petsync-86790',
    authDomain: 'petsync-86790.firebaseapp.com',
    storageBucket: 'petsync-86790.firebasestorage.app',
    measurementId: 'G-DR7C9X3M6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjeA4BJ55MxOf4hEYNDdJJJTgnFcmb9pA',
    appId: '1:452972580172:android:553dc97ce8cb05f7e853e9',
    messagingSenderId: '452972580172',
    projectId: 'petsync-86790',
    storageBucket: 'petsync-86790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuPBSaj5tSuYhIrUymjKF0hkvj3wB1X6M',
    appId: '1:452972580172:ios:64506fa9c1da5ef8e853e9',
    messagingSenderId: '452972580172',
    projectId: 'petsync-86790',
    storageBucket: 'petsync-86790.firebasestorage.app',
    iosBundleId: 'com.example.petsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuPBSaj5tSuYhIrUymjKF0hkvj3wB1X6M',
    appId: '1:452972580172:ios:64506fa9c1da5ef8e853e9',
    messagingSenderId: '452972580172',
    projectId: 'petsync-86790',
    storageBucket: 'petsync-86790.firebasestorage.app',
    iosBundleId: 'com.example.petsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaEyNLQCzuruMWAV6JpH6tQWHdbeGkgq4',
    appId: '1:452972580172:web:549aff752a7142e0e853e9',
    messagingSenderId: '452972580172',
    projectId: 'petsync-86790',
    authDomain: 'petsync-86790.firebaseapp.com',
    storageBucket: 'petsync-86790.firebasestorage.app',
    measurementId: 'G-Q1EYM58803',
  );
}
